version: 2

sources:
  - name: raw
    description: Rohdaten
    schema: gz_raw_data
    tables:
      - name: sales
        description: sales data
        identifier: raw_gz_sales_copy
        columns:
          - name: date_date
            description: date_of_purchase
          - name: orders_id
            description: unique id of orders
          - name: products_id
            description: unique id of products
          - name: revenue
            description: Einnahmen
          - name: quantity
            description: nb of products sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        description: Product Data
        identifier: raw_gz_product_copy
        columns:
          - name: products_id
            description: Unique ID of Product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: Float of purchasing price
      - name: ship
        description: Shipping Data
        identifier: raw_gz_ship_copy
        columns:
          - name: orders_id
            description: unique id of orders
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: paid by the customer
          - name: logcost
            description: logistics cost
          - name: ship_cost
            description: shipping cost
      - name: adwords
        description: Adwords Data
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: Datum der Kampagne
          - name: paid_source
            description: Quelle der bezahlten Anzeige
          - name: campaign_key
            description: Schl端ssel zur Kampagne
          - name: camPGN_name
            description: Name der Kampagne
          - name: ads_cost
            description: Kosten der Anzeigenkampagne
          - name: impression
            description: Anzahl der Impressionen
          - name: click
            description: Anzahl der Klicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key || '_' || paid_source)"
          - not_null:
              column_name:
                - date_date
                - campaign_key
                - paid_source

      - name: bing
        description: Bing Data
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: Datum der Kampagne
          - name: paid_source
            description: Quelle der bezahlten Anzeige
          - name: campaign_key
            description: Schl端ssel zur Kampagne
          - name: camPGN_name
            description: Name der Kampagne
          - name: ads_cost
            description: Kosten der Anzeigenkampagne
          - name: impression
            description: Anzahl der Impressionen
          - name: click
            description: Anzahl der Klicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key || '_' || paid_source)"
          - not_null:
              column_name:
                - date_date
                - campaign_key
                - paid_source

      - name: criteo
        description: Criteo Data
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: Datum der Kampagne
          - name: paid_source
            description: Quelle der bezahlten Anzeige
          - name: campaign_key
            description: Schl端ssel zur Kampagne
          - name: camPGN_name
            description: Name der Kampagne
          - name: ads_cost
            description: Kosten der Anzeigenkampagne
          - name: impression
            description: Anzahl der Impressionen
          - name: click
            description: Anzahl der Klicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key || '_' || paid_source)"
          - not_null:
              column_name:
                - date_date
                - campaign_key
                - paid_source

      - name: facebook
        description: Facebook Data
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: Datum der Kampagne
          - name: paid_source
            description: Quelle der bezahlten Anzeige
          - name: campaign_key
            description: Schl端ssel zur Kampagne
          - name: camPGN_name
            description: Name der Kampagne
          - name: ads_cost
            description: Kosten der Anzeigenkampagne
          - name: impression
            description: Anzahl der Impressionen
          - name: click
            description: Anzahl der Klicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key || '_' || paid_source)"
          - not_null:
              column_name:
                - date_date
                - campaign_key
                - paid_source
